version: '3.8'

services:
  postgres:
    image: postgres
    container_name: votehub
    restart: always
    environment:
      POSTGRES_USER: xsainteer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votehub
    ports:
      - "5432:5432"
        
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: